backend:
  name: git-gateway
  branch: main

site_url: https://neu.grabenfleck.de

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "page"
    label: "Page"
    folder: "/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
