backend:
  name: git-gateway
  branch: main

site_url: https://neu.grabenfleck.de
locale: "de"
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: page
    label: Seite
    folder: "src/pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: vorstand
    label: Vorstand
    folder: src/pages
    delete: false
    extension: mdx
    format: frontmatter
    editor:
      preview: false
    files:
      - name: "Vorstand Seite"
        label: "Vorstand Seite MDX"
        file: "src/pages/vorstand1.mdx"
        description: Vorstandsliste als MDX
        fields:
          - label: "Name"
            name: name
            widget: "string"
          - label: "Rolle"
            name: role
            widget: "string"
          - label: "Image Path"
            name: image
            widget: "string"
            hint: "Full image path"
